$schema: "http://json-schema.org/draft-07/schema#"
$ref: "#/definitions/root"

definitions:
  #---------------------------------------------------------
  # Root
  #---------------------------------------------------------
  root:
    type: object
    properties:
      namespace:
        type: string
      suffix:
        type: string
      output_dir:
        type: string
      classes:
        type: array
        items:
          $ref: "#/definitions/Class"
    required:
      - suffix
  #---------------------------------------------------------
  # Class
  #---------------------------------------------------------
  Class:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      namespace:
        type: string
      templates:
        type: array
        items:
          $ref: '#/definitions/TemplateMeta'
      user_variables:
        $ref: "#/definitions/UserVariables"
    required:
    - name
    - templates
  #---------------------------------------------------------
  # Template Meta
  #---------------------------------------------------------
  TemplateMeta:
    type: object
    properties:
      name:
        type: string
      output_dir:
        type: string
    required:
      - name
  #---------------------------------------------------------
  # User Variables
  #---------------------------------------------------------
  UserVariables:
    type: object
    properties:
      __allow_any_key_values__:
        type: string
